services:
  
  postgres: 
    image: postgres:17-bullseye
    restart: always
    container_name: postgres
    env_file:
      .env
    ports:
      - 5432:5432

  django:
    container_name: django
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - postgres
  